

# Notes: 
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: The Zhang Laboratory
description: "The laboratory of Dr. Hanrui Zhang at Columbia University Irving Medical Center"
keywords: "github, github-pages, websites, laboratory, macrophage"

# author settings for cc-by
author: hanrui zhang
pub_year: 2019
github_username: hanruiclear

# add the full url for the github repository
repo: "https://github.com/hanruizhang/hanruizhang.github.io"

# urls
# your webpage url: https://username.github.io
url: https://hanruizhang.github.io
# your repository name: /repository
baseurl: /ZhangLab

# analytics if desired (and use environment variable on build command)
google_analytics: UA-74844011-1

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown

theme: jekyll-theme-slate
